### ISSUE TITLE
Latest build (2.2) TypeError: list indices must be integers, not str.

### ISSUE THREAD

**Issue by gargomoma** [Vinz87/TndrAssistant#7]
Happens running the latest build, i had to rollback to v2.1.4

```
2017-01-20 17:07:17	list indices must be integers, not str
Traceback (most recent call last):
  File "TndrAssistant.py", line 118, in <module>
    users = [result["user"] for result in api_res["results"]]
TypeError: list indices must be integers, not str
2017-01-20 17:07:18	list indices must be integers, not str
Traceback (most recent call last):
  File "TndrAssistant.py", line 118, in <module>
    users = [result["user"] for result in api_res["results"]]
TypeError: list indices must be integers, not str
2017-01-20 17:07:18	list indices must be integers, not str
Traceback (most recent call last):
  File "TndrAssistant.py", line 118, in <module>
    users = [result["user"] for result in api_res["results"]]
TypeError: list indices must be integers, not str
Traceback (most recent call last):
  File "TndrAssistant.py", line 126, in <module>
    console_logger.debug("# users: %s", len(users))
NameError: name 'users' is not defined

```

**Comment by Vinz87** [comment]
This happens when recs are exhausted, made more clear in last version.
